import { Payment,columns } from "./columns";
import { DataTable } from "./data-table";

const getData = async (): Promise<Payment[]> => {
 
return [
  {
    id: "728ed521",
    userId: "usr_a7f3k92m",
    amount: 134,
    status: "pending",
    fullName: "John Doe",
    email: "johndoe@gmail.com",
  },
  {
    id: "728ed522",
    userId: "usr_b4x8p17q",
    amount: 124,
    status: "success",
    fullName: "Jane Doe",
    email: "janedoe@gmail.com",
  },
  {
    id: "728ed523",
    userId: "usr_c9m2v63r",
    amount: 167,
    status: "success",
    fullName: "Mike Galloway",
    email: "mikegalloway@gmail.com",
  },
  {
    id: "728ed524",
    userId: "usr_d5q7n41x",
    amount: 156,
    status: "failed",
    fullName: "Minerva Robinson",
    email: "minerbarobinson@gmail.com",
  },
  {
    id: "728ed525",
    userId: "usr_e8k3p95w",
    amount: 145,
    status: "success",
    fullName: "Mable Clayton",
    email: "mableclayton@gmail.com",
  },
  {
    id: "728ed526",
    userId: "usr_f2r6m84z",
    amount: 189,
    status: "pending",
    fullName: "Nathan McDaniel",
    email: "nathanmcdaniel@gmail.com",
  },
  {
    id: "728ed527",
    userId: "usr_g7x1q52n",
    amount: 178,
    status: "success",
    fullName: "Myrtie Lamb",
    email: "myrtielamb@gmail.com",
  },
  {
    id: "728ed528",
    userId: "usr_h3v9k27p",
    amount: 190,
    status: "success",
    fullName: "Leona Bryant",
    email: "leonabryant@gmail.com",
  },
  {
    id: "728ed529",
    userId: "usr_i6n4w81s",
    amount: 134,
    status: "failed",
    fullName: "Aaron Willis",
    email: "aaronwillis@gmail.com",
  },
  {
    id: "728ed52a",
    userId: "usr_j8p2r46m",
    amount: 543,
    status: "success",
    fullName: "Joel Keller",
    email: "joelkeller@gmail.com",
  },
  {
    id: "728ed52b",
    userId: "usr_k5z7x13q",
    amount: 234,
    status: "pending",
    fullName: "Daniel Ellis",
    email: "danielellis@gmail.com",
  },
  {
    id: "728ed52c",
    userId: "usr_m9q3v68r",
    amount: 345,
    status: "success",
    fullName: "Gordon Kennedy",
    email: "gordonkennedy@gmail.com",
  },
  {
    id: "728ed52d",
    userId: "usr_n4w8k25x",
    amount: 335,
    status: "failed",
    fullName: "Emily Hoffman",
    email: "emilyhoffman@gmail.com",
  },
  {
    id: "728ed52e",
    userId: "usr_p7r1m93z",
    amount: 664,
    status: "pending",
    fullName: "Jeffery Garrett",
    email: "jefferygarrett@gmail.com",
  },
  {
    id: "728ed52f",
    userId: "usr_q2x6n47k",
    amount: 332,
    status: "success",
    fullName: "Ralph Baker",
    email: "ralphbaker@gmail.com",
  },
  {
    id: "728ed52g",
    userId: "usr_r8m4p72v",
    amount: 413,
    status: "failed",
    fullName: "Seth Fields",
    email: "sethfields@gmail.com",
  },
  {
    id: "728ed52h",
    userId: "usr_s3k9q15w",
    amount: 345,
    status: "pending",
    fullName: "Julia Webb",
    email: "juliawebb@gmail.com",
  },
  {
    id: "728ed52i",
    userId: "usr_t6v2x84n",
    amount: 754,
    status: "success",
    fullName: "Gary Banks",
    email: "garybanks@gmail.com",
  },
  {
    id: "728ed52j",
    userId: "usr_u9p5m31r",
    amount: 643,
    status: "failed",
    fullName: "Flora Chambers",
    email: "florachambers@gmail.com",
  },
  {
    id: "728ed52k",
    userId: "usr_v4q8k67x",
    amount: 543,
    status: "pending",
    fullName: "Steve Hanson",
    email: "stevehanson@gmail.com",
  },
  {
    id: "728ed52l",
    userId: "usr_w7n3r92p",
    amount: 324,
    status: "success",
    fullName: "Lola Robinson",
    email: "lolarobinson@gmail.com",
  },
  {
    id: "728ed52m",
    userId: "usr_x2m6v48q",
    amount: 123,
    status: "pending",
    fullName: "Ethel Waters",
    email: "ethelwaters@gmail.com",
  },
  {
    id: "728ed52n",
    userId: "usr_y8p4k17s",
    amount: 422,
    status: "failed",
    fullName: "Grace Edwards",
    email: "graceedwards@gmail.com",
  },
  {
    id: "728ed52o",
    userId: "usr_z5r9n63m",
    amount: 712,
    status: "success",
    fullName: "Sallie Wong",
    email: "salliewong@gmail.com",
  },
  {
    id: "728ed52p",
    userId: "usr_a3v7q81x",
    amount: 360,
    status: "success",
    fullName: "Bryan Gutierrez",
    email: "bryangutierrez@gmail.com",
  },
  {
    id: "728ed52q",
    userId: "usr_b6m2p94w",
    amount: 454,
    status: "pending",
    fullName: "Erik Rice",
    email: "erikrice@gmail.com",
  },
  {
    id: "728ed52r",
    userId: "usr_c8x5k37n",
    amount: 382,
    status: "success",
    fullName: "Jordan Atkins",
    email: "jordanatkins@gmail.com",
  },
  {
    id: "728ed52s",
    userId: "usr_d1q9v62p",
    amount: 328,
    status: "failed",
    fullName: "Bill Brewer",
    email: "billbrewer@gmail.com",
  },
  {
    id: "728ed52t",
    userId: "usr_e4n7m15r",
    amount: 250,
    status: "success",
    fullName: "Edwin Morris",
    email: "edwinmorris@gmail.com",
  },
  {
    id: "728ed52u",
    userId: "usr_f9p3x86k",
    amount: 658,
    status: "success",
    fullName: "Harold Becker",
    email: "haroldbecker@gmail.com",
  },
  {
    id: "728ed52v",
    userId: "usr_g2v8q41m",
    amount: 691,
    status: "success",
    fullName: "Hannah Rodriguez",
    email: "hannahrodriguez@gmail.com",
  },
  {
    id: "728ed52w",
    userId: "usr_h5k1r73x",
    amount: 969,
    status: "success",
    fullName: "Zachary Beck",
    email: "zacharybeck@gmail.com",
  },
  {
    id: "728ed52x",
    userId: "usr_i7m4p92q",
    amount: 617,
    status: "failed",
    fullName: "Frances Potter",
    email: "francespotter@gmail.com",
  },
  {
    id: "728ed52y",
    userId: "usr_j3x8n56v",
    amount: 173,
    status: "success",
    fullName: "Raymond Murray",
    email: "raymondmurray@gmail.com",
  },
  {
    id: "728ed52z",
    userId: "usr_k6q2m84p",
    amount: 843,
    status: "success",
    fullName: "Adam Sherman",
    email: "adamsherman@gmail.com",
  },
  {
    id: "728ed521f",
    userId: "usr_m9v5r31x",
    amount: 914,
    status: "pending",
    fullName: "Anne Cruz",
    email: "annecruz@gmail.com",
  },
];


};

const PaymentsPage = async () => {
  const data = await getData();
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">All Payments</h1>
      </div>
      <DataTable columns={columns} data={data}/>
    </div>
  );
};

export default PaymentsPage;
